#!/bin/sh

# http://mark-story.com/posts/view/using-git-commit-hooks-to-prevent-stupid-mistakes
if git-rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

RED='\033[0;31m'
NC='\033[0m' # No Color

for FILE in `git diff-index --name-status $against --| grep -v ".rasb$" |grep -v Gemfile |grep -v web_steps.rb |grep -v env.rb | cut -c3-` ; do
    # Check if the file contains 'debugger'
    if [ `grep 'debugger' $FILE -c ` == "1" ]
    then
     printf "${RED} $FILE contains debugger\n"
     exit 1
    fi

if [ `grep 'binding.pry' $FILE -c ` == "1" ]
    then
     printf "${RED} $FILE contains binding.pry\n"
     exit 1
    fi

    if [ `grep 'console.debug' $FILE -c ` == "1" ]
    then
     echo $FILE ' contains console.debug!'
     exit 1
    fi

done
